#%RAML 1.0
title: Your fourth root
version: v1
baseUri: http://{host}:8081/second/{version}
baseUriParameters:
  host:
    description: The host machine's IP address
protocols: HTTP
mediaType: application/json # default media type
documentation: 
  - title: What Am I?
    content:
      This time, that Mule flow will actually
      return a json object, because the default
      media type is application/json. This can
      be changed at the method level.
types:
  Screen:
    properties:
      version:
        type: string
  Mouse:
    properties:
      purpose:
        type: string
      wire:
        type: string
traits:
  secured:
    usage: Apply this to any method that needs to be secured
    description: Some requests require authentication.
    headers:
      access_token:
        description: Access Token
        example: 5757gh76
        required: true

/my-resource:
  get:
    responses:
      200:
        body:
          example:
            Screen:
              version: LED
            Mouse:
              purpose: Gaming
              wire: Wireless
